import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import ResultsMedia from '../components/ResultsMedia';
import requests from '../utils/requests';

// gets rendered() on the client after SSR async function getServerSideProps(context)
// we now have props available to pass into the Home Component
  // destructure resultsMedia into desired data
export default function Home({ resultsMedia }) {
  console.log(resultsMedia)
  return (
    <div>
      <Head>
        <title>react-next-clone-hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER COMPONENT */}
      <Header></Header>

      {/* NAVBAR */}
      <Navbar></Navbar>

      {/* RESULTS */}
      {/* pass in the resultsMedia as a prop to the ResultsMedia Component */}
      <ResultsMedia resultsMedia={resultsMedia}></ResultsMedia>

    </div>
  )
};

// async function getServerSideProps(context) gets rendered first before we return the html to the user 
// gets rendered() on the server
export async function getServerSideProps(context) {
  // get genre from the url
  const genre = context.query.genre;
  // make a request to the DB
    // asysnc function so use await keyword with fetch to make a get Request to the TMDB server
    // use optional chaining to protect from unexpected error || revert to trending category
    // then() pass a aResultMedia json object 
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  .then((aResultMedia) => aResultMedia.json());
  // return aResultMedia (resultsMedia) json object data as a prop to our component from the request
  return {
    props: {
      resultsMedia: request.results,
    }
  }
};
